### ISSUE TITLE
Unable to connect to server error on 3DS

### ISSUE THREAD

**Issue by SepticRedhead** [PretendoNetwork/juxtaposition-ui#35]
Keep getting unable to connect to server error when trying to enter miiverse

**Comment by TheGhostboi64** [comment]
The server is down, or the public beta isnt including 3DS juxt.

**Comment by SuperErnD** [comment]
> The server is down, or the public beta isnt including 3DS juxt.

Server is down, maybe 
![image](https://user-images.githubusercontent.com/84639576/193232262-fe6234dc-f1bc-4e91-ae1c-cb30768683dd.png)
(https://juxt.pretendo.cc)

**Comment by Linkdash2019** [comment]
My connection is NOT private!
