### ISSUE TITLE
hardcoded stuff and missing config file on ui-redesign branch

### ISSUE THREAD

**Issue by Komfudo** [PretendoNetwork/juxtaposition-ui#43]
the address for the S3 storage is hardcoded: https://github.com/PretendoNetwork/juxtaposition-ui/blob/ui-redesign/src/util.js#LL37C1-L37C1

The static EJS files are also hardcoded of pretendo's url.

**Comment by jonbarrow** [comment]
Closing as that branch no longer exists and the mentioned values are not hard coded in the latest development branches
