### ISSUE TITLE
Error on cmd

### ISSUE THREAD

**Issue by ghost** [PretendoNetwork/juxtaposition-ui#61]
![image](https://github.com/PretendoNetwork/juxtaposition-ui/assets/116295141/2d505283-2cbb-49da-8ec3-35feeb0eef56)

**Comment by ttdu08off** [comment]
Help me pls

**Comment by 00cedke** [comment]
mdrrrrrrrrr t la toi enft

**Comment by jonbarrow** [comment]
`npm i -g rimraf`

**Comment by jonbarrow** [comment]
Closing as OPs account is deleted and no further information was given
