### ISSUE TITLE
[Bug]: Embed meta tags load on removed posts

### ISSUE THREAD

**Issue by superfever3000** [PretendoNetwork/juxtaposition-ui#68]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

When you remove a post on Juxtaposition, then visit it on the web, it says "Post has been removed"
However, if you take a look at the head in the HTML, it still contains embed metadata that embeds the post in other places.

### What did you expect to happen?

I expect the embed meta tags to not be present, as the website clearly defines the post being removed.

### Steps to reproduce?

Look at any deleted post, then look at the head in the HTML.
Optionally, attempt to send the link to a place like a Discord channel and watch it embed.
![image](https://github.com/PretendoNetwork/juxtaposition-ui/assets/100550441/e3e821a9-6805-457e-b846-0934bc0a0071)
Screenshot was taken today, post was deleted a while ago

**Comment by superfever3000** [comment]
![image](https://github.com/PretendoNetwork/juxtaposition-ui/assets/100550441/e3e821a9-6805-457e-b846-0934bc0a0071)
sorry, made a typo on the image part

**Comment by CaramelKat** [comment]
Fixed in [60730f3](https://github.com/PretendoNetwork/juxtaposition-ui/commit/60730f3d10fe9013a9037e66dbd7dde79fa3fd74). Closing.
