### ISSUE TITLE
[Bug]: Incorrect Greece time

### ISSUE THREAD

**Issue by dracula99gr** [PretendoNetwork/juxtaposition-ui#69]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

When I open miiverse the time seems -1:00 off
![20240615_174825](https://github.com/PretendoNetwork/juxtaposition-ui/assets/20153526/b84461ca-3388-481d-839a-ce84feb3b82f)
![Screenshot_20240615-174906_Chrome](https://github.com/PretendoNetwork/juxtaposition-ui/assets/20153526/f47ba07f-6db6-4cf3-bcbd-187147ae304c)

### What did you expect to happen?

The correct time for my country was expected to be seen.

**Comment by jonbarrow** [comment]
This is not an issue with Juxtaposition. See https://github.com/Nightkingale/Wii-U-Time-Sync/issues/21 for details. This was an issue on NN as well, and is a result of accurate emulation

**Comment by dracula99gr** [comment]
hello @jonbarrow is it related to the [miiverse api](https://github.com/PretendoNetwork/miiverse-api) or is it related with something else?

**Comment by jonbarrow** [comment]
This is not an issue at all. As I said this is how Nintendo Network also functioned, and we cannot guarantee that there are not systems which rely on the assumption that it functions like this. So we emulate it accurately.

**Comment by dracula99gr** [comment]
But the correct time was shown before miiverse shutdown. If the issue is not on the sysmodule, is not on miiverse, is not on pretendo, then it doesn't exist? What about the fact that it's wrong? Is it really normal that miiverse time is different than system time?

**Comment by jonbarrow** [comment]
Yes. It's normal. Again, this is how Nintendo Network functioned. I linked to an existing issue on another repository about this exact topic which has more details, including a link showing this happening on Nintendo Network a decade ago.
