### ISSUE TITLE
[Feature]: Rules Page

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [PretendoNetwork/juxtaposition-ui#72]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

Juxt needs a rules page, so all users know what's allowed and what is not allowed.
Mainly an issue for all members that aren't on the discord.
Maybe make it show once on registering and make it re-visitable later somewhere.

### Why do you want to have this feature?

There has likely been some rule breakers who probably didn't know they break an rule.

**Comment by DanGN0** [comment]
Would be especially useful for rules that differ from Miiverse. Per example: friend code/socials sharing, swearing (?)... etc
