### ISSUE TITLE
[Enhancement]: Begin using title_ids in Juxt communities to allow games to start posting to Juxt

### ISSUE THREAD

**Issue by ItzSwirlz** [PretendoNetwork/juxtaposition-ui#76]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What enhancement would you like to see?

On the current database, for communities designated to specific games, please give the community its corresponding Title ID in the database so games can start posting to juxt.

For a list of title IDs I've compiled: https://gist.github.com/ItzSwirlz/dfc69a5a465599212c22680e210e3ca9

### Any other details to share? (OPTIONAL)

I said in Discord:

"Basically, when a game (that is nice, not all games are like this but nintendo land is one of those nice ones) does a post to miiverse, it looks for a community to post it under. It does this by looking for a certain title_id in the juxt communities. I think you can choose which community but for argument sake, there's only one. However currently, no communities have that title_id set to its correct value. So if a dev goes into the DB, sets that field under the Nintendo Land juxt community to what it should be, it will work"

Nintendo Land happens to be one of those games that doesn't need a server - all it needs is to find a community with its title ID to post.

Super Mario 3D World needs its server to be up and running and a community with its correct title id to be tagged for its Miiverse posting functionality to work. Wii Fit U, same.

This is not really a code issue - it's more of a request to start putting Title IDs in so people can post to Juxt from in-game. I've confirmed this working locally.

**Note: Make sure the community in its json file has its permissions schema located (at least the one with the minimum post permission level) otherwise it will crash the miiverse-api. Creating new communities by default for me did not seem to include these.**

**Comment by jonbarrow** [comment]
This is not the right repository for this. This is not an issue with the user interface of the applet, it's about the in-game API. The correct repository would be https://github.com/PretendoNetwork/miiverse-api

> On the current database, for communities designated to specific games, please give the community its corresponding Title ID in the database so games can start posting to juxt.
> ...
> However currently, no communities have that title_id set to its correct value

I'm not sure what you mean here? All of our communities *DO* have title IDs assigned to them, and games like Super Mario 3D World have been working for a long time now https://twitter.com/PretendoNetwork/status/1643303763942203403

I've manually checked the database and there is not a single community which doesn't have at least 1 title ID already set:

![Screenshot from 2024-07-04 20-05-34](https://github.com/PretendoNetwork/juxtaposition-ui/assets/27011796/ff3c3449-07d3-40fa-9627-8752114667a5)

> For a list of title IDs I've compiled

These are just the decimal representations of the game's title IDs. Every (retail) Wii U title ID is already known https://wiiubrew.org/wiki/Title_database. For example `1407375153045504` is just decimal for `5000010102000`, which is the title ID for Nintendo Land USA (`00050000-10102000`)

> it's more of a request to start putting Title IDs in so people can post to Juxt from in-game.

Our database already has these set. `title_id` is an array of title IDs, for different regions, and every community has them. Including Nintendo Land, which was made 2 years ago:

![Screenshot from 2024-07-04 20-11-35](https://github.com/PretendoNetwork/juxtaposition-ui/assets/27011796/d2ead173-14bb-487e-a6d2-e892e95b2634)

> Make sure the community in its json file has its permissions schema located (at least the one with the minimum post permission level) otherwise it will crash the miiverse-api. Creating new communities by default for me did not seem to include these.

There are no JSON files for any of this, I'm very confused as to what you mean here. I'm not really sure what the issue being reported here is, or what your supposed solution is?

**Comment by ItzSwirlz** [comment]
Trace and I on discord think it may be permission level related - Trace seems to be able to post to Nintendo Land from in-game on his account. What's the post perms level? But good to know the title ids are not just weird, they're decimal representations and that they're already in there

**Comment by ItzSwirlz** [comment]
Closing since it is most likely the wrong repository. The question really is, is the ability to post from in-game determined by beta tester status?
